import { Component, inject, signal, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatTabsModule } from '@angular/material/tabs';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatChipsModule } from '@angular/material/chips';
import { StateService } from '../../services/state.service';
import { ApiService } from '../../services/api.service';
import { I18nService } from '../../services/i18n.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatCardModule,
    MatButtonModule,
    MatIconModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatTabsModule,
    MatSnackBarModule,
    MatProgressSpinnerModule,
    MatChipsModule,
  ],
  template: `
    <div class="login-container">
      <mat-tab-group [(selectedIndex)]="tabIndex">
        <mat-tab [label]="t()('login')">
          <div class="tab-content">
            @if (loginMethod() === 'password') {
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>{{ t()('email') }}</mat-label>
                <input matInput [(ngModel)]="loginAddress">
              </mat-form-field>
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>{{ t()('password') }}</mat-label>
                <input matInput type="password" [(ngModel)]="loginPassword">
              </mat-form-field>
            } @else {
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>{{ t()('credential') }}</mat-label>
                <textarea matInput [(ngModel)]="credential" rows="3"></textarea>
              </mat-form-field>
            }
            
            @if (state.openSettings().enableAddressPassword) {
              <div class="text-center mb-2">
                <button mat-button color="primary" (click)="toggleLoginMethod()">
                  {{ loginMethod() === 'password' ? t()('credentialLogin') : t()('passwordLogin') }}
                </button>
              </div>
            }
            
            <button mat-flat-button color="primary" class="full-width" (click)="login()" [disabled]="loading()">
              <mat-icon>email</mat-icon>
              {{ t()('login') }}
            </button>
            
            @if (showNewAddressTab()) {
              <button mat-stroked-button class="full-width mt-2" (click)="tabIndex = 1">
                <mat-icon>add</mat-icon>
                {{ t()('getNewEmail') }}
              </button>
            }
          </div>
        </mat-tab>
        
        @if (showNewAddressTab()) {
          <mat-tab [label]="t()('getNewEmail')">
            <div class="tab-content">
              @if (!state.openSettings().disableCustomAddressName) {
                <p class="hint-text">{{ t()('getNewEmailTip1') }}</p>
                <p class="hint-text">{{ t()('getNewEmailTip2') }}</p>
              }
              <p class="hint-text">{{ t()('getNewEmailTip3') }}</p>
              
              @if (!state.openSettings().disableCustomAddressName) {
                <button mat-button color="primary" (click)="generateName()" class="mb-2">
                  <mat-icon>refresh</mat-icon>
                  {{ t()('generateName') }}
                </button>
              }
              
              <div class="email-form">
                @if (addressPrefix()) {
                  <mat-chip>{{ addressPrefix() }}</mat-chip>
                }
                @if (!state.openSettings().disableCustomAddressName) {
                  <mat-form-field appearance="outline" class="name-field">
                    <input matInput [(ngModel)]="emailName" [maxlength]="state.openSettings().maxAddressLen || 30">
                  </mat-form-field>
                } @else {
                  <mat-form-field appearance="outline" class="name-field">
                    <input matInput [value]="t()('autoGeneratedName')" disabled>
                  </mat-form-field>
                }
                <span class="at-symbol">@</span>
                <mat-form-field appearance="outline" class="domain-field">
                  <mat-select [(ngModel)]="emailDomain">
                    @for (domain of domainsOptions(); track domain.value) {
                      <mat-option [value]="domain.value">{{ domain.label }}</mat-option>
                    }
                  </mat-select>
                </mat-form-field>
              </div>
              
              <button mat-flat-button color="primary" class="full-width mt-3" (click)="newEmail()" [disabled]="loading()">
                <mat-icon>add</mat-icon>
                {{ t()('getNewEmail') }}
              </button>
            </div>
          </mat-tab>
        }
        
        <mat-tab [label]="t()('help')">
          <div class="tab-content">
            <div class="info-alert">
              <mat-icon>info</mat-icon>
              {{ t()('pleaseGetNewEmail') }}
            </div>
          </div>
        </mat-tab>
      </mat-tab-group>
    </div>
  `,
  styles: [`
    .login-container { max-width: 600px; margin: 0 auto; }
    .tab-content { padding: 16px 0; }
    .full-width { width: 100%; }
    .mt-2 { margin-top: 8px; }
    .mt-3 { margin-top: 12px; }
    .mb-2 { margin-bottom: 8px; }
    .text-center { text-align: center; }
    .hint-text { color: #666; font-size: 14px; margin-bottom: 8px; }
    .email-form { 
      display: flex; 
      align-items: center; 
      gap: 8px; 
      flex-wrap: wrap;
      margin-top: 16px;
    }
    .name-field { flex: 1; min-width: 120px; }
    .domain-field { min-width: 150px; }
    .at-symbol { font-size: 18px; font-weight: bold; }
    .info-alert {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 16px;
      background: #e3f2fd;
      border-radius: 4px;
      color: #1565c0;
    }
  `]
})
export class LoginComponent implements OnInit {
  state = inject(StateService);
  private api = inject(ApiService);
  private i18n = inject(I18nService);
  private snackBar = inject(MatSnackBar);
  private router = inject(Router);

  t = this.i18n.t;
  tabIndex = 0;
  loading = signal(false);
  loginMethod = signal<'password' | 'credential'>('credential');
  
  credential = '';
  loginAddress = '';
  loginPassword = '';
  emailName = '';
  emailDomain = '';

  ngOnInit() {
    if (this.state.openSettings().enableAddressPassword) {
      this.loginMethod.set('password');
    }
    const domains = this.domainsOptions();
    if (domains.length > 0) {
      this.emailDomain = domains[0].value;
    }
  }

  toggleLoginMethod() {
    this.loginMethod.set(this.loginMethod() === 'password' ? 'credential' : 'password');
  }

  showNewAddressTab = () => this.state.openSettings().enableUserCreateEmail;
  
  addressPrefix = () => this.state.openSettings().prefix || '';
  
  domainsOptions = () => this.state.openSettings().domains || [];

  async login() {
    this.loading.set(true);
    try {
      if (this.loginMethod() === 'password') {
        if (!this.loginAddress || !this.loginPassword) {
          this.snackBar.open(this.t()('emailPasswordRequired'), 'OK', { duration: 3000 });
          return;
        }
        const res: any = await this.api.addressLogin(this.loginAddress, this.loginPassword).toPromise();
        if (res?.jwt) {
          this.state.setJwt(res.jwt);
          await this.loadSettings();
        }
      } else {
        if (!this.credential) {
          this.snackBar.open(this.t()('credentialInput'), 'OK', { duration: 3000 });
          return;
        }
        this.state.setJwt(this.credential);
        await this.loadSettings();
      }
    } catch (e: any) {
      this.snackBar.open(e.message || 'Login failed', 'OK', { duration: 3000 });
    } finally {
      this.loading.set(false);
    }
  }

  async newEmail() {
    this.loading.set(true);
    try {
      const nameToSend = this.state.openSettings().disableCustomAddressName ? '' : this.emailName;
      const res: any = await this.api.newAddress({
        name: nameToSend,
        domain: this.emailDomain
      }).toPromise();
      if (res?.jwt) {
        this.state.setJwt(res.jwt);
        await this.loadSettings();
        this.snackBar.open('Email created successfully!', 'OK', { duration: 3000 });
      }
    } catch (e: any) {
      this.snackBar.open(e.message || 'Failed to create email', 'OK', { duration: 3000 });
    } finally {
      this.loading.set(false);
    }
  }

  generateName() {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let name = '';
    for (let i = 0; i < 8; i++) {
      name += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    this.emailName = name;
  }

  private async loadSettings() {
    try {
      const data: any = await this.api.getSettings().toPromise();
      this.state.settings.set({
        fetched: true,
        address: data.address || '',
        sendBalance: data.send_balance || 0,
        autoReply: data.auto_reply,
      });
    } catch (e) {
      // ignore
    }
  }
}
