import { Injectable, computed } from '@angular/core';
import { StateService } from './state.service';

const translations: Record<string, Record<string, string>> = {
  zh: {
    // Common
    'title': '临时邮箱',
    'loading': '加载中...',
    'save': '保存',
    'cancel': '取消',
    'delete': '删除',
    'confirm': '确认',
    'copy': '复制',
    'copied': '已复制',
    'refresh': '刷新',
    'search': '搜索',
    'noData': '暂无数据',
    'success': '成功',
    'error': '错误',
    'enable': '启用',
    'test': '测试',
    'text': '文本',
    'send': '发送',
    'name': '名称',
    'content': '内容',
    
    // Header
    'home': '首页',
    'admin': '管理',
    'user': '用户',
    'about': '关于',
    'appearance': '外观',
    'login': '登录',
    'logout': '退出',
    
    // Index
    'mailbox': '收件箱',
    'sendbox': '发件箱',
    'sendmail': '发邮件',
    'settings': '设置',
    'autoReply': '自动回复',
    'webhook': 'Webhook',
    'accountSettings': '账户设置',
    
    // Address
    'createAddress': '创建地址',
    'addressName': '地址名称',
    'selectDomain': '选择域名',
    'password': '密码',
    'passwordOptional': '密码（可选）',
    'currentAddress': '当前地址',
    'deleteAddress': '删除地址',
    'confirmDeleteAddress': '确定删除此地址？',
    'addressManage': '地址管理',
    'changeAddress': '更换地址',
    'fetchAddressError': '邮箱地址凭证无效或邮箱地址不存在，也可能是网络连接异常，请稍后再尝试。',
    'addressCredential': '邮箱地址凭证',
    'addressCredentialTip': '请复制邮箱地址凭证，你可以使用它登录你的邮箱。',
    'showAddressCredential': '查看邮箱地址凭证',
    
    // Login
    'credential': '邮箱地址凭据',
    'credentialInput': '请输入邮箱地址凭据',
    'credentialLogin': '凭据登录',
    'passwordLogin': '密码登录',
    'email': '邮箱',
    'emailPasswordRequired': '邮箱和密码不能为空',
    'getNewEmail': '创建新邮箱',
    'getNewEmailTip1': '请输入你想要使用的邮箱地址',
    'getNewEmailTip2': '留空将会生成一个随机的邮箱地址。',
    'getNewEmailTip3': '你可以从下拉列表中选择一个域名。',
    'generateName': '生成随机名字',
    'autoGeneratedName': '自动生成名称',
    'help': '帮助',
    'pleaseGetNewEmail': '请"登录"或点击 "注册新邮箱" 按钮来获取一个新的邮箱地址',
    
    // Mail
    'from': '发件人',
    'to': '收件人',
    'subject': '主题',
    'date': '日期',
    'attachments': '附件',
    'noSubject': '(无主题)',
    'prevMail': '上一封',
    'nextMail': '下一封',
    'reply': '回复',
    'forward': '转发',
    'download': '下载',
    'pleaseSelectMail': '请选择邮件',
    
    // Auto Refresh
    'autoRefresh': '自动刷新',
    'refreshAfter': '{msg}秒后刷新',
    
    // Multi Action
    'multiAction': '批量操作',
    'cancelMultiAction': '取消批量',
    'selectAll': '全选',
    'unselectAll': '取消全选',
    
    // Admin
    'account': '账户',
    'statistics': '统计',
    'mails': '邮件',
    'maintenance': '维护',
    'quickSetup': '快速设置',
    'database': '数据库',
    'telegram': '电报机器人',
    
    // Auth
    'enterPassword': '请输入密码',
    'adminPassword': '管理员密码',
    
    // Account Settings
    'changePassword': '修改密码',
    'newPassword': '新密码',
    'confirmPassword': '确认密码',
    'passwordMismatch': '密码不匹配',
    'passwordChanged': '密码修改成功',
    'clearInbox': '清空收件箱',
    'clearSentItems': '清空发件箱',
    'clearInboxConfirm': '确定要清空你收件箱中的所有邮件吗？',
    'clearSentItemsConfirm': '确定要清空你发件箱中的所有邮件吗？',
    'deleteAccount': '删除账户',
    'deleteAccountConfirm': '确定要删除你的账户和其中的所有邮件吗?',
    'logoutConfirm': '确定要退出登录吗？',
    
    // Send Mail
    'fromName': '你的名称',
    'toName': '收件人名称',
    'sendBalance': '剩余发送邮件额度',
    'requestAccess': '申请权限',
    'requestAccessTip': '您需要申请权限才能发送邮件',
    'successSend': '请查看您的发件箱',
    
    // Auto Reply
    'autoReplySettings': '自动回复设置',
    'enableAutoReply': '启用自动回复',
    'sourcePrefix': '来源邮件前缀',
    'autoReplyMessage': '自动回复内容',
    
    // Webhook
    'webhookNotEnabled': 'Webhook 未开启',
    'messagePusherDemo': '填入MessagePusher示例',
    'fillInDemoTip': '请修改URL和其他设置为您自己的配置',
    'urlMissing': 'URL 不能为空',
    
    // Appearance
    'darkMode': '深色模式',
    'language': '语言',
    'useIframeShowMail': '使用iframe显示HTML邮件',
    'preferShowTextMail': '默认以文本显示邮件',
    'autoRefreshInterval': '自动刷新间隔(秒)',
    'useUTCDate': '使用 UTC 时间',
    
    // User Page
    'currentUser': '当前登录用户',
    'fetchUserSettingsError': '登录信息已过期或账号不存在，也可能是网络连接异常，请稍后再尝试。',
    'addressManagement': '地址管理',
    'userMailBox': '收件箱',
    'userSettings': '用户设置',
    'bindAddress': '绑定邮箱地址',
    'address': '地址',
    'createOrBind': '创建或绑定',
    'mailCount': '邮件数量',
    'sendCount': '发送数量',
    'actions': '操作',
    'changeMailAddress': '切换地址',
    'transferAddress': '转移地址',
    'unbindAddress': '解绑地址',
    'transferAddressTip': '转移地址到其他用户将会从你的账户中移除此地址并转移给其他用户。确定要转移地址吗？',
    'targetUserEmail': '目标用户邮箱',
    'unbindAddressTip': '解绑前请切换到此邮箱地址并保存邮箱地址凭证。',
    'addressQueryTip': '留空查询所有地址',
    'allAddresses': '所有地址',
    'query': '查询',
    'showPasskeyList': '查看 Passkey 列表',
    'createPasskey': '创建 Passkey',
    'passwordTip': '服务器只会接收到密码的哈希值，不会接收到明文密码，因此无法查看或者找回您的密码, 如果管理员启用了邮件验证您可以在无痕模式重置密码',
    'passkeyName': 'Passkey 名称',
    'passkeyNamePlaceholder': '请输入 Passkey 名称或者留空自动生成',
    'createdAt': '创建时间',
    'renamePasskey': '重命名 Passkey',
    'deletePasskey': '删除 Passkey',
    'renamePasskeyPlaceholder': '请输入新的 Passkey 名称',
  },
  en: {
    // Common
    'title': 'Temp Mail',
    'loading': 'Loading...',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'copy': 'Copy',
    'copied': 'Copied',
    'refresh': 'Refresh',
    'search': 'Search',
    'noData': 'No data',
    'success': 'Success',
    'error': 'Error',
    'enable': 'Enable',
    'test': 'Test',
    'text': 'Text',
    'send': 'Send',
    'name': 'Name',
    'content': 'Content',
    
    // Header
    'home': 'Home',
    'admin': 'Admin',
    'user': 'User',
    'about': 'About',
    'appearance': 'Appearance',
    'login': 'Login',
    'logout': 'Logout',
    
    // Index
    'mailbox': 'Inbox',
    'sendbox': 'Sent',
    'sendmail': 'Compose',
    'settings': 'Settings',
    'autoReply': 'Auto Reply',
    'webhook': 'Webhook',
    'accountSettings': 'Account Settings',
    
    // Address
    'createAddress': 'Create Address',
    'addressName': 'Address Name',
    'selectDomain': 'Select Domain',
    'password': 'Password',
    'passwordOptional': 'Password (optional)',
    'currentAddress': 'Current Address',
    'deleteAddress': 'Delete Address',
    'confirmDeleteAddress': 'Are you sure to delete this address?',
    'addressManage': 'Address Manage',
    'changeAddress': 'Change Address',
    'fetchAddressError': 'Mail address credential is invalid or account not exist.',
    'addressCredential': 'Mail Address Credential',
    'addressCredentialTip': 'Please copy the Mail Address Credential to login.',
    'showAddressCredential': 'Show Address Credential',
    
    // Login
    'credential': 'Email Address Credential',
    'credentialInput': 'Please input the Mail Address Credential',
    'credentialLogin': 'Credential Login',
    'passwordLogin': 'Password Login',
    'email': 'Email',
    'emailPasswordRequired': 'Email and password are required',
    'getNewEmail': 'Create New Email',
    'getNewEmailTip1': 'Please input the email you want to use',
    'getNewEmailTip2': 'Leaving it blank will generate a random email address.',
    'getNewEmailTip3': 'You can choose a domain from the dropdown list.',
    'generateName': 'Generate Fake Name',
    'autoGeneratedName': 'Auto-generated name',
    'help': 'Help',
    'pleaseGetNewEmail': 'Please login or click "Get New Email" button',
    
    // Mail
    'from': 'From',
    'to': 'To',
    'subject': 'Subject',
    'date': 'Date',
    'attachments': 'Attachments',
    'noSubject': '(No Subject)',
    'prevMail': 'Previous',
    'nextMail': 'Next',
    'reply': 'Reply',
    'forward': 'Forward',
    'download': 'Download',
    'pleaseSelectMail': 'Please select a mail',
    
    // Auto Refresh
    'autoRefresh': 'Auto Refresh',
    'refreshAfter': 'Refresh in {msg}s',
    
    // Multi Action
    'multiAction': 'Multi Select',
    'cancelMultiAction': 'Cancel',
    'selectAll': 'Select All',
    'unselectAll': 'Unselect All',
    
    // Admin
    'account': 'Account',
    'statistics': 'Statistics',
    'mails': 'Mails',
    'maintenance': 'Maintenance',
    'quickSetup': 'Quick Setup',
    'database': 'Database',
    'telegram': 'Telegram Bot',
    
    // Auth
    'enterPassword': 'Please enter password',
    'adminPassword': 'Admin Password',
    
    // Account Settings
    'changePassword': 'Change Password',
    'newPassword': 'New Password',
    'confirmPassword': 'Confirm Password',
    'passwordMismatch': 'Passwords do not match',
    'passwordChanged': 'Password changed successfully',
    'clearInbox': 'Clear Inbox',
    'clearSentItems': 'Clear Sent Items',
    'clearInboxConfirm': 'Are you sure to clear all emails in your inbox?',
    'clearSentItemsConfirm': 'Are you sure to clear all sent items?',
    'deleteAccount': 'Delete Account',
    'deleteAccountConfirm': 'Are you sure to delete your account?',
    'logoutConfirm': 'Are you sure to logout?',
    
    // Send Mail
    'fromName': 'Your Name',
    'toName': 'Recipient Name',
    'sendBalance': 'Send Mail Balance Left',
    'requestAccess': 'Request Access',
    'requestAccessTip': 'You need to request access to send mail',
    'successSend': 'Please check your sendbox',
    
    // Auto Reply
    'autoReplySettings': 'Auto Reply Settings',
    'enableAutoReply': 'Enable Auto Reply',
    'sourcePrefix': 'Source Mail Prefix',
    'autoReplyMessage': 'Auto Reply Message',
    
    // Webhook
    'webhookNotEnabled': 'Webhook is not enabled',
    'messagePusherDemo': 'Fill with Message Pusher Demo',
    'fillInDemoTip': 'Please modify the URL and settings',
    'urlMissing': 'URL is required',
    
    // Appearance
    'darkMode': 'Dark Mode',
    'language': 'Language',
    'useIframeShowMail': 'Use iframe to show HTML mail',
    'preferShowTextMail': 'Display text mail by default',
    'autoRefreshInterval': 'Auto Refresh Interval (Sec)',
    'useUTCDate': 'Use UTC Date',
    
    // User Page
    'currentUser': 'Current Login User',
    'fetchUserSettingsError': 'Login password is invalid or account not exist, it may be network connection issue, please try again later.',
    'addressManagement': 'Address Management',
    'userMailBox': 'Mail Box',
    'userSettings': 'User Settings',
    'bindAddress': 'Bind Mail Address',
    'address': 'Address',
    'createOrBind': 'Create or Bind',
    'mailCount': 'Mail Count',
    'sendCount': 'Send Count',
    'actions': 'Actions',
    'changeMailAddress': 'Change Address',
    'transferAddress': 'Transfer Address',
    'unbindAddress': 'Unbind Address',
    'transferAddressTip': 'Transfer address to another user will remove the address from your account and transfer it to another user. Are you sure to transfer the address?',
    'targetUserEmail': 'Target User Email',
    'unbindAddressTip': 'Before unbinding, please switch to this email address and save the email address credential.',
    'addressQueryTip': 'Leave blank to query all addresses',
    'allAddresses': 'All Addresses',
    'query': 'Query',
    'showPasskeyList': 'Show Passkey List',
    'createPasskey': 'Create Passkey',
    'passwordTip': 'The server will only receive the hash value of the password, and will not receive the plaintext password, so it cannot view or retrieve your password. If the administrator enables email verification, you can reset the password in incognito mode',
    'passkeyName': 'Passkey Name',
    'passkeyNamePlaceholder': 'Please enter the passkey name or leave it empty to generate a random one',
    'createdAt': 'Created At',
    'renamePasskey': 'Rename Passkey',
    'deletePasskey': 'Delete Passkey',
    'renamePasskeyPlaceholder': 'Please enter the new passkey name',
  }
};

@Injectable({
  providedIn: 'root'
})
export class I18nService {
  constructor(private state: StateService) {}

  t = computed(() => {
    const locale = this.state.locale();
    return (key: string, params?: Record<string, string>) => {
      let text = translations[locale]?.[key] || translations['en']?.[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, v);
        });
      }
      return text;
    };
  });
}
