import { Injectable, computed } from '@angular/core';
import { StateService } from './state.service';

const translations: Record<string, Record<string, string>> = {
  zh: {
    // Common
    'title': '临时邮箱',
    'loading': '加载中...',
    'save': '保存',
    'cancel': '取消',
    'delete': '删除',
    'confirm': '确认',
    'copy': '复制',
    'copied': '已复制',
    'refresh': '刷新',
    'search': '搜索',
    'noData': '暂无数据',
    'success': '成功',
    'error': '错误',
    
    // Header
    'home': '首页',
    'admin': '管理',
    'user': '用户',
    'about': '关于',
    'appearance': '外观',
    'login': '登录',
    'logout': '退出',
    
    // Index
    'mailbox': '收件箱',
    'sendbox': '发件箱',
    'sendmail': '发邮件',
    'settings': '设置',
    'autoReply': '自动回复',
    'webhook': 'Webhook',
    
    // Address
    'createAddress': '创建地址',
    'addressName': '地址名称',
    'selectDomain': '选择域名',
    'password': '密码',
    'passwordOptional': '密码（可选）',
    'currentAddress': '当前地址',
    'deleteAddress': '删除地址',
    'confirmDeleteAddress': '确定删除此地址？',
    'addressManage': '地址管理',
    'changeAddress': '更换地址',
    'fetchAddressError': '邮箱地址凭证无效或邮箱地址不存在，也可能是网络连接异常，请稍后再尝试。',
    
    // Login
    'credential': '邮箱地址凭据',
    'credentialInput': '请输入邮箱地址凭据',
    'credentialLogin': '凭据登录',
    'passwordLogin': '密码登录',
    'email': '邮箱',
    'emailPasswordRequired': '邮箱和密码不能为空',
    'getNewEmail': '创建新邮箱',
    'getNewEmailTip1': '请输入你想要使用的邮箱地址',
    'getNewEmailTip2': '留空将会生成一个随机的邮箱地址。',
    'getNewEmailTip3': '你可以从下拉列表中选择一个域名。',
    'generateName': '生成随机名字',
    'autoGeneratedName': '自动生成名称',
    'help': '帮助',
    'pleaseGetNewEmail': '请"登录"或点击 "注册新邮箱" 按钮来获取一个新的邮箱地址',
    
    // Mail
    'from': '发件人',
    'to': '收件人',
    'subject': '主题',
    'date': '日期',
    'attachments': '附件',
    'noSubject': '(无主题)',
    'prevMail': '上一封',
    'nextMail': '下一封',
    'reply': '回复',
    'forward': '转发',
    'download': '下载',
    'pleaseSelectMail': '请选择邮件',
    
    // Auto Refresh
    'autoRefresh': '自动刷新',
    'refreshAfter': '{msg}秒后刷新',
    
    // Multi Action
    'multiAction': '批量操作',
    'cancelMultiAction': '取消批量',
    'selectAll': '全选',
    'unselectAll': '取消全选',
    
    // Admin
    'account': '账户',
    'statistics': '统计',
    'mails': '邮件',
    'maintenance': '维护',
    
    // Auth
    'enterPassword': '请输入密码',
    'adminPassword': '管理员密码',
  },
  en: {
    // Common
    'title': 'Temp Mail',
    'loading': 'Loading...',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'copy': 'Copy',
    'copied': 'Copied',
    'refresh': 'Refresh',
    'search': 'Search',
    'noData': 'No data',
    'success': 'Success',
    'error': 'Error',
    
    // Header
    'home': 'Home',
    'admin': 'Admin',
    'user': 'User',
    'about': 'About',
    'appearance': 'Appearance',
    'login': 'Login',
    'logout': 'Logout',
    
    // Index
    'mailbox': 'Inbox',
    'sendbox': 'Sent',
    'sendmail': 'Compose',
    'settings': 'Settings',
    'autoReply': 'Auto Reply',
    'webhook': 'Webhook',
    
    // Address
    'createAddress': 'Create Address',
    'addressName': 'Address Name',
    'selectDomain': 'Select Domain',
    'password': 'Password',
    'passwordOptional': 'Password (optional)',
    'currentAddress': 'Current Address',
    'deleteAddress': 'Delete Address',
    'confirmDeleteAddress': 'Are you sure to delete this address?',
    'addressManage': 'Address Manage',
    'changeAddress': 'Change Address',
    'fetchAddressError': 'Mail address credential is invalid or account not exist, it may be network connection issue, please try again later.',
    
    // Login
    'credential': 'Email Address Credential',
    'credentialInput': 'Please input the Mail Address Credential',
    'credentialLogin': 'Credential Login',
    'passwordLogin': 'Password Login',
    'email': 'Email',
    'emailPasswordRequired': 'Email and password are required',
    'getNewEmail': 'Create New Email',
    'getNewEmailTip1': 'Please input the email you want to use',
    'getNewEmailTip2': 'Leaving it blank will generate a random email address.',
    'getNewEmailTip3': 'You can choose a domain from the dropdown list.',
    'generateName': 'Generate Fake Name',
    'autoGeneratedName': 'Auto-generated name',
    'help': 'Help',
    'pleaseGetNewEmail': 'Please login or click "Get New Email" button to get a new email address',
    
    // Mail
    'from': 'From',
    'to': 'To',
    'subject': 'Subject',
    'date': 'Date',
    'attachments': 'Attachments',
    'noSubject': '(No Subject)',
    'prevMail': 'Previous',
    'nextMail': 'Next',
    'reply': 'Reply',
    'forward': 'Forward',
    'download': 'Download',
    'pleaseSelectMail': 'Please select a mail',
    
    // Auto Refresh
    'autoRefresh': 'Auto Refresh',
    'refreshAfter': 'Refresh in {msg}s',
    
    // Multi Action
    'multiAction': 'Multi Select',
    'cancelMultiAction': 'Cancel',
    'selectAll': 'Select All',
    'unselectAll': 'Unselect All',
    
    // Admin
    'account': 'Account',
    'statistics': 'Statistics',
    'mails': 'Mails',
    'maintenance': 'Maintenance',
    
    // Auth
    'enterPassword': 'Please enter password',
    'adminPassword': 'Admin Password',
  }
};

@Injectable({
  providedIn: 'root'
})
export class I18nService {
  constructor(private state: StateService) {}

  t = computed(() => {
    const locale = this.state.locale();
    return (key: string, params?: Record<string, string>) => {
      let text = translations[locale]?.[key] || translations['en']?.[key] || key;
      if (params) {
        Object.entries(params).forEach(([k, v]) => {
          text = text.replace(`{${k}}`, v);
        });
      }
      return text;
    };
  });
}
